webtalk_init -webtalk_dir C:\\Users\\Chris\\Desktop\\GitHub\\ensc-452\\AudioTutorial\\first_zynq_design\\first_zynq_design.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jan 18 22:04:23 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "213300772_0_0_473" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9l1rd3h6fh1htvn8872k50g8aq" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.1_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3696 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1737263479154" -context "sdk\\\\hardware/1737263479154"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1737263479154"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1737263479154"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.1" -context "sdk\\\\hardware/1737263479154"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1737263479154"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1737263479154"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1737263479154"
webtalk_add_data -client sdk -key uid -value "1737263504329" -context "sdk\\\\bsp/1737263504329"
webtalk_add_data -client sdk -key hwid -value "1737263479154" -context "sdk\\\\bsp/1737263504329"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1737263504329"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1737263504329"
webtalk_add_data -client sdk -key uid -value "1737263506042" -context "sdk\\\\application/1737263506042"
webtalk_add_data -client sdk -key hwid -value "1737263479154" -context "sdk\\\\application/1737263506042"
webtalk_add_data -client sdk -key bspid -value "1737263504329" -context "sdk\\\\application/1737263506042"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1737263506042"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1737263506042"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1737263506042"
webtalk_transmit -clientid 3516230690 -regid "213300772_0_0_473" -xml C:\\Users\\Chris\\Desktop\\GitHub\\ensc-452\\AudioTutorial\\first_zynq_design\\first_zynq_design.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Chris\\Desktop\\GitHub\\ensc-452\\AudioTutorial\\first_zynq_design\\first_zynq_design.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Chris\\Desktop\\GitHub\\ensc-452\\AudioTutorial\\first_zynq_design\\first_zynq_design.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
