# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: u:/ENSC 452/VGA_tutorial/vga_tutorial_students/vga_controller_ip/vga_controller_ip.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet
